### PR TITLE
Document setters precedence & showcase it's usage

### PR DESCRIPTION
**Pull request by pablojimpas**

### CODE REVIEW

**Comment by jpnurmi** [comment]
Hey @pablojimpas, are you able to sign the CLA? This repo is going to be transferred to the Canonical org later.

**Comment by pablojimpas** [comment]
> Hey @pablojimpas, are you able to sign the CLA? This repo is going to be transferred to the Canonical org later.

Aah I missed this check.

I generally dislike signing CLAs specially for something like this but I will do it just in case I want contribute more significant stuff on Flutter related projects by Canonical.

**Comment by jpnurmi** [comment]
Thanks, and sorry for the inconvenience. The CLA might take a day or two to sync. I'll poke the CI to rerun the check later.

**Comment by pablojimpas** [comment]
> The CLA might take a day or two to sync.

Mmmm I thought I did something wrong and I've just pushed another minor commit to trigger the CI 🙃

> I'll poke the CI to rerun the check later.

Okey, perfect!

**Review by jpnurmi — APPROVED** [review]
Thanks, LGTM :+1:

**Pull request merged**
